"use client";

import Image from "next/image";
import { TTestResult } from "../../lib/db"; // Ensure this matches your db.ts export!

interface AnalysisViewProps {
  ttestData: TTestResult[];
}

export function AnalysisView({ ttestData }: AnalysisViewProps) {
  return (
    <div className="space-y-8 font-sans">
      <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded text-sm text-blue-800">
        <strong>Pre-Computed Analysis:</strong> Melanoma patients receiving Miraclib (PBMC samples only).
      </div>

      {/* 1. Display the Seaborn Image generated by Python */}
      <div className="bg-white border rounded-lg shadow-sm p-4 w-full flex justify-center">
        <Image 
          src="/boxplot.png" 
          alt="Seaborn Boxplot" 
          width={900} 
          height={500} 
          className="object-contain"
          // unoptimized is used so Next.js doesn't cache the old image if you re-run the python script
          unoptimized 
        />
      </div>

      {/* 2. Display the T-Test Stats from SQLite */}
      <div className="border border-gray-200 rounded-lg shadow-sm bg-white overflow-hidden">
        <div className="bg-gray-100 px-4 py-3 border-b border-gray-200">
          <h3 className="font-semibold text-gray-700">T-Test Results (Significance: p &lt; 0.05)</h3>
        </div>
        <table className="w-full text-left text-sm">
          <thead className="bg-gray-50 border-b">
            <tr>
              <th className="px-4 py-2">Cell Population</th>
              <th className="px-4 py-2">P-Value</th>
              <th className="px-4 py-2">Significant Difference?</th>
            </tr>
          </thead>
          <tbody>
            {ttestData && ttestData.length > 0 ? (
              ttestData.map((row) => (
                <tr key={row.population} className="border-b hover:bg-gray-50">
                  <td className="px-4 py-2 font-medium">{row.population}</td>
                  <td className="px-4 py-2">{Number(row.p_value).toExponential(4)}</td>
                  <td className="px-4 py-2">
                    {row.is_significant === "YES" ? (
                      <span className="text-green-600 font-bold">Yes</span>
                    ) : (
                      <span className="text-gray-500">No</span>
                    )}
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan={3} className="px-4 py-4 text-center text-gray-500">
                  No statistical data found. Please run the Python analysis script.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}